/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author pedro
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        getContentPane().setBackground(new java.awt.Color(102, 102, 102));
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuCompras = new javax.swing.JMenu();
        itmSolicitarCompra = new javax.swing.JMenuItem();
        itmCancelarCompra = new javax.swing.JMenuItem();
        mnuEstoque = new javax.swing.JMenu();
        itmConsularEstoque = new javax.swing.JMenuItem();
        itmAtualizarEstoque = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenu();
        itmAlterarP = new javax.swing.JMenuItem();
        itmCadastrarP = new javax.swing.JMenuItem();
        itmExcluirP = new javax.swing.JMenuItem();
        mnuRelatorios = new javax.swing.JMenu();
        itmRelatorioEstoque = new javax.swing.JMenuItem();
        itmRelatorioProdutos = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setBackground(new java.awt.Color(102, 102, 102));
        getContentPane().setLayout(null);

        mnuCompras.setText("Compras");

        itmSolicitarCompra.setText("Solicitar compra");
        mnuCompras.add(itmSolicitarCompra);

        itmCancelarCompra.setText("Cancelar compra");
        itmCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCancelarCompraActionPerformed(evt);
            }
        });
        mnuCompras.add(itmCancelarCompra);

        jMenuBar2.add(mnuCompras);

        mnuEstoque.setText("Estoque");

        itmConsularEstoque.setText("Consultar estoque");
        mnuEstoque.add(itmConsularEstoque);

        itmAtualizarEstoque.setText("Atualizar estoque");
        mnuEstoque.add(itmAtualizarEstoque);

        jMenuBar2.add(mnuEstoque);

        mnuProdutos.setText("Produtos");

        itmAlterarP.setText("Alterar produto");
        itmAlterarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarPActionPerformed(evt);
            }
        });
        mnuProdutos.add(itmAlterarP);

        itmCadastrarP.setText("Cadastrar produto");
        mnuProdutos.add(itmCadastrarP);

        itmExcluirP.setText("Excluir produto");
        mnuProdutos.add(itmExcluirP);

        jMenuBar2.add(mnuProdutos);

        mnuRelatorios.setText("Relatórios");

        itmRelatorioEstoque.setText("Emitir Relatório Estoque");
        itmRelatorioEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRelatorioEstoqueActionPerformed(evt);
            }
        });
        mnuRelatorios.add(itmRelatorioEstoque);

        itmRelatorioProdutos.setText("Emitir Relatório Produtos");
        itmRelatorioProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmRelatorioProdutosActionPerformed(evt);
            }
        });
        mnuRelatorios.add(itmRelatorioProdutos);

        jMenuBar2.add(mnuRelatorios);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(656, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCancelarCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmCancelarCompraActionPerformed

    private void itmAlterarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itmAlterarPActionPerformed

    private void itmRelatorioProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRelatorioProdutosActionPerformed
        new RelatoriosProdutos().setVisible(true);
    }//GEN-LAST:event_itmRelatorioProdutosActionPerformed

    private void itmRelatorioEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmRelatorioEstoqueActionPerformed
        new RelatoriosEstoque().setVisible(true);
    }//GEN-LAST:event_itmRelatorioEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmAlterarP;
    private javax.swing.JMenuItem itmAtualizarEstoque;
    private javax.swing.JMenuItem itmCadastrarP;
    private javax.swing.JMenuItem itmCancelarCompra;
    private javax.swing.JMenuItem itmConsularEstoque;
    private javax.swing.JMenuItem itmExcluirP;
    private javax.swing.JMenuItem itmRelatorioEstoque;
    private javax.swing.JMenuItem itmRelatorioProdutos;
    private javax.swing.JMenuItem itmSolicitarCompra;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenu mnuCompras;
    private javax.swing.JMenu mnuEstoque;
    private javax.swing.JMenu mnuProdutos;
    private javax.swing.JMenu mnuRelatorios;
    // End of variables declaration//GEN-END:variables
}
